[package]
name = "archive-rclick"
version = "1.0.0"
edition = "2024"
rust-version = "1.92"
description = "A fast, lightweight Windows archive manager built with Rust, Slint, and libarchive"
license = "MIT"
publish = false
build = "build.rs"

[lib]
name = "archive_rclick_core"
crate-type = ["rlib", "cdylib"]

[dependencies]
slint = { version = "=1.17.1", default-features = false, features = [
    "std",
    "compat-1-2",
    "backend-winit",
    "renderer-femtovg",
    "accessibility",
    "unstable-winit-030",
] }
thiserror = "2.0.18"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Globalization",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_Ole",
    "Win32_System_Registry",
    "Win32_System_SystemServices",
    "Win32_System_Time",
    "Win32_UI_HiDpi",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
    "Win32_UI_WindowsAndMessaging",
] }
windows-core = "0.61"
raw-window-handle = "0.6.2"

[build-dependencies]
sha2 = "=0.10.9"
slint-build = "=1.17.1"
embed-resource = "=3.0.9"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"
